### PR TITLE
run on django 3.0

### PR DESCRIPTION
**Pull request by miltonmce**
I hope it works for you as well, I will make a refactor if you are interested

### CODE REVIEW

**Comment by janzaheer** [comment]
Thanks @miltonmce thats a cool contribution, what I am thinking now is to upgrade the python version, I want to upgrade it to 3.6.

what do you suggest?

**Comment by miltonmce** [comment]
try it! :3

**Comment by miltonmce** [comment]
i hope you like it 

https://ibb.co/fvMJRCK

**Comment by janzaheer** [comment]
Thats cool,

I have few more projects will add them in git and let you know

**Pull request merged**
